name: flutter_campus_connected
description: A new Flutter project.

version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.11.1+6
  cloud_firestore: ^0.12.5
  firebase_storage: ^3.0.1
  #firebase_core: ^0.4.0+5
  transparent_image:
  connectivity:
  image_picker:
  #  google_maps_flutter:
  #  location:
  datetime_picker_formfield:

  cupertino_icons: ^0.1.2
  #firebase_database: ^3.0.2
  font_awesome_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
    - assets/gallery.png
    - assets/person.jpg
    - assets/loadingfailed.png


flutter_icons:
  #android: "launcher_icon"
  #ios: true
  #image_path: "icon/icon.png"