name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_auth: ^0.6.6
  firebase_database: ^1.0.5
  font_awesome_flutter: "^8.0.1"


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true




  assets:
    - assets/flutter-icon.png






flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"