name: HMCommunity
description: An App to initialize or join Events made by Students for Students from the University for applied Sciences Munich

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: any
  path_provider: "^0.5.0+1"
  rxdart: ^0.21.0
  share: ^0.6.0+1
  http: "0.12.0+2"
  font_awesome_flutter: "^8.0.1"
  #business logic component (bloc)
  bloc: ^0.12.0
  flutter_bloc: ^0.11.1
  equatable: ^0.2.0
#  user_repository:
#    path: user_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"